POST http://localhost:8888/api/product
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "productName": "Sprite",
  "amountAvailable": 3,
  "cost": 1.85
}



